In [71]:
!git config --global user.name "megiva"
!git config --global user.email "meghana.m.ivaturi@gmail.com"
organization = 'Break-Through-Tech'
repo = 'Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems'
repo_url = f"https://github.com/{organization}/{repo}.git"
!git clone {repo_url}

Cloning into 'Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems'...
remote: Enumerating objects: 169, done.
remote: Counting objects: 100% (169/169), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 169 (delta 73), reused 96 (delta 27), pack-reused 0 (from 0)
Receiving objects: 100% (169/169), 3.94 MiB | 13.09 MiB/s, done.
Resolving deltas: 100% (73/73), done.

In [72]:
%cd {repo}

/content/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems

In [73]:
!ls

Challenge-Project-Overview.md  Documentation.md		       notebooks
copernicusmarine	       Getting-Started-for-Fellows.md  README.md
data			       literature		       requirements.txt

In [74]:
!git branch -a

* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/NoneventsTask
  remotes/origin/classifier
  remotes/origin/eda
  remotes/origin/evaluation
  remotes/origin/feature/copernicus-statistics
  remotes/origin/feature/integrate-environmental-features
  remotes/origin/feature/lfo-cross-validation
  remotes/origin/feature/logistic-regression-baseline
  remotes/origin/main

In [75]:
!git switch -c task3-data-splitting

Switched to a new branch 'task3-data-splitting'

In [76]:
!pwd
!git branch --show-current
!ls data/processed/

/content/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems
task3-data-splitting
copernicus_matching_errors.csv
copernicus_physics_features.csv
environmental_feature_integration_summary.csv
hab_events_with_environmental_features.csv
hab_model_dataset_initial.csv
hab_model_dataset_methodology.json
harmful_algae_events_standardized.csv
synthetic_non_event_candidates.csv
synthetic_non_event_errors.csv

In [77]:
import pandas as pd

model_df = pd.read_csv(
    "data/processed/hab_model_dataset_initial.csv"
)

env_df = pd.read_csv(
    "data/processed/hab_events_with_environmental_features.csv"
)

print("Model dataset:", model_df.shape)
print("Environmental dataset:", env_df.shape)

Model dataset: (194, 26)
Environmental dataset: (194, 25)

In [78]:
print("MODEL DATASET COLUMNS:")
print(model_df.columns.tolist())

print("\nENVIRONMENTAL DATASET COLUMNS:")
print(env_df.columns.tolist())

MODEL DATASET COLUMNS:
['record_id', 'target', 'sample_type', 'is_synthetic', 'observation_date', 'latitude', 'longitude', 'country', 'region', 'haedat_row_id', 'source_event_id', 'matched_positive_record_id', 'synthetic_method', 'date_source', 'copernicus_date', 'date_difference_hours', 'area_buffer_degrees', 'surface_depth_m', 'thetao_valid_cells', 'thetao_mean', 'thetao_p95', 'thetao_variance', 'so_valid_cells', 'so_mean', 'so_p95', 'so_variance']

ENVIRONMENTAL DATASET COLUMNS:
['record_id', 'target', 'sample_type', 'is_synthetic', 'observation_date', 'latitude', 'longitude', 'country', 'region', 'haedat_row_id', 'source_event_id', 'matched_positive_record_id', 'date_source', 'copernicus_date', 'date_difference_hours', 'area_buffer_degrees', 'surface_depth_m', 'thetao_valid_cells', 'so_valid_cells', 'thetao_mean', 'thetao_p95', 'thetao_variance', 'so_mean', 'so_p95', 'so_variance']

In [79]:
display(model_df.head())
display(env_df.head())

,record_id,target,sample_type,is_synthetic,observation_date,latitude,longitude,country,region,haedat_row_id,...,area_buffer_degrees,surface_depth_m,thetao_valid_cells,thetao_mean,thetao_p95,thetao_variance,so_valid_cells,so_mean,so_p95,so_variance
0,non_event_7_1,0,synthetic_non_event,True,2006-04-25,59.256572,10.499640,NORWAY,Region 12 (EUR),NaN,...,1.0,0.494025,254,6.908690,7.532731,0.090125,254,31.094096,33.424406,5.015275
1,event_23,1,haedat_event,False,2026-02-13,11.224200,125.565500,PHILIPPINES,NaN,23.0,...,1.0,0.494025,391,28.082365,28.566149,0.157069,391,33.844508,34.112064,0.313781
2,non_event_89_1,0,synthetic_non_event,True,2000-06-27,58.424444,8.756944,NORWAY,NaN,NaN,...,1.0,0.494025,313,13.195018,13.865114,0.149155,313,30.440136,33.596606,2.618113
3,event_53,1,haedat_event,False,2025-02-15,-16.994000,-142.251000,FRENCH POLYNESIA,NaN,53.0,...,1.0,0.494025,559,29.210604,29.331040,0.004621,559,35.871442,35.990631,0.004497
4,event_99,1,haedat_event,False,2025-02-25,12.195100,123.453400,PHILIPPINES,NaN,99.0,...,1.0,0.494025,425,27.367620,27.849379,0.048506,425,34.005727,34.417249,0.171228

,record_id,target,sample_type,is_synthetic,observation_date,latitude,longitude,country,region,haedat_row_id,...,area_buffer_degrees,surface_depth_m,thetao_valid_cells,so_valid_cells,thetao_mean,thetao_p95,thetao_variance,so_mean,so_p95,so_variance
0,non_event_51_1,0,synthetic_non_event,True,1993-02-22,-16.994000,-142.251000,FRENCH POLYNESIA,NaN,NaN,...,1.0,0.494025,559,559,27.905239,28.177441,0.019787,35.742680,35.897549,0.006027
1,non_event_91_1,0,synthetic_non_event,True,1993-03-24,58.424444,8.756944,NORWAY,NaN,NaN,...,1.0,0.494025,313,313,4.425948,5.749632,0.418288,31.660774,35.104221,2.972819
2,non_event_70_1,0,synthetic_non_event,True,1993-03-28,-9.276000,-139.746000,FRENCH POLYNESIA,NaN,NaN,...,1.0,0.494025,575,575,28.991751,29.104715,0.004113,35.668670,35.743278,0.002008
3,non_event_94_1,0,synthetic_non_event,True,1993-06-29,58.730278,9.216667,NORWAY,NaN,NaN,...,1.0,0.494025,298,298,14.113277,14.654946,0.145899,29.384076,30.873440,0.976555
4,non_event_29_1,0,synthetic_non_event,True,1994-03-05,-34.680000,135.630000,AUSTRALIA,Region 5 (ANZ),NaN,...,1.0,0.494025,416,416,18.454598,20.176916,0.880420,35.830575,36.766030,0.342330

In [80]:
print(model_df["target"].value_counts())

print("\nTarget percentages:")
print(model_df["target"].value_counts(normalize=True) * 100)

print("\nDate range:")
print(model_df["observation_date"].min())
print(model_df["observation_date"].max())

target
0    97
1    97
Name: count, dtype: int64

Target percentages:
target
0    50.0
1    50.0
Name: proportion, dtype: float64

Date range:
1993-02-22
2026-06-01

In [81]:
print("Sample types:")
print(model_df["sample_type"].value_counts(dropna=False))

print("\nSynthetic records:")
print(model_df["is_synthetic"].value_counts(dropna=False))

print("\nMatched positive IDs:")
print(model_df["matched_positive_record_id"].notna().sum())

print("\nMissing dates:")
print(model_df["observation_date"].isna().sum())

print("\nDuplicate record IDs:")
print(model_df["record_id"].duplicated().sum())

Sample types:
sample_type
synthetic_non_event    97
haedat_event           97
Name: count, dtype: int64

Synthetic records:
is_synthetic
True     97
False    97
Name: count, dtype: int64

Matched positive IDs:
97

Missing dates:
0

Duplicate record IDs:
0

In [82]:
model_df["observation_date"] = pd.to_datetime(
    model_df["observation_date"],
    errors="coerce"
)

print("Earliest date:", model_df["observation_date"].min())
print("Latest date:", model_df["observation_date"].max())

print("\nObservations by year:")
print(
    model_df["observation_date"]
    .dt.year
    .value_counts()
    .sort_index()
)

Earliest date: 1993-02-22 00:00:00
Latest date: 2026-06-01 00:00:00

Observations by year:
observation_date
1993     4
1994     3
1995     6
1996     7
1997     5
1998     6
1999     6
2000     1
2001     7
2002     6
2003     7
2005     4
2006     2
2007     2
2008     2
2009     2
2010     1
2011     7
2013     1
2014     1
2015     2
2016     2
2017     1
2018     4
2020     3
2021     1
2025    69
2026    32
Name: count, dtype: int64

In [83]:
# Separate real HAB events and synthetic non-events
positive_df = model_df[model_df["target"] == 1].copy()
negative_df = model_df[model_df["target"] == 0].copy()

print("Positive dates by year:")
print(positive_df["observation_date"].dt.year.value_counts().sort_index())

print("\nNegative dates by year:")
print(negative_df["observation_date"].dt.year.value_counts().sort_index())

print("\nExample synthetic records:")
display(
    negative_df[
        ["record_id", "matched_positive_record_id",
         "observation_date", "synthetic_method"]
    ].head(10)
)

Positive dates by year:
observation_date
2025    69
2026    28
Name: count, dtype: int64

Negative dates by year:
observation_date
1993    4
1994    3
1995    6
1996    7
1997    5
1998    6
1999    6
2000    1
2001    7
2002    6
2003    7
2005    4
2006    2
2007    2
2008    2
2009    2
2010    1
2011    7
2013    1
2014    1
2015    2
2016    2
2017    1
2018    4
2020    3
2021    1
2026    4
Name: count, dtype: int64

Example synthetic records:

,record_id,matched_positive_record_id,observation_date,synthetic_method
0,non_event_7_1,event_7,2006-04-25,same_location_and_month_outside_spatiotemporal...
2,non_event_89_1,event_89,2000-06-27,same_location_and_month_outside_spatiotemporal...
5,non_event_82_1,event_82,2008-03-26,same_location_and_month_outside_spatiotemporal...
8,non_event_4_1,event_4,1999-04-03,same_location_and_month_outside_spatiotemporal...
9,non_event_46_1,event_46,2016-04-19,same_location_and_month_outside_spatiotemporal...
10,non_event_92_1,event_92,2018-06-23,same_location_and_month_outside_spatiotemporal...
14,non_event_64_1,event_64,1995-03-03,same_location_and_month_outside_spatiotemporal...
15,non_event_51_1,event_51,1993-02-22,same_location_and_month_outside_spatiotemporal...
17,non_event_23_1,event_23,2001-02-20,same_location_and_month_outside_spatiotemporal...
18,non_event_15_1,event_15,2005-01-15,same_location_and_month_outside_spatiotemporal...

In [84]:
positive_ids = set(positive_df["record_id"])

matched_ids = set(
    negative_df["matched_positive_record_id"].dropna()
)

print("Synthetic parent IDs found in positive records:",
      len(matched_ids & positive_ids))

print("Unique synthetic parent IDs:", len(matched_ids))

print("Unmatched parent IDs:", len(matched_ids - positive_ids))

Synthetic parent IDs found in positive records: 97
Unique synthetic parent IDs: 97
Unmatched parent IDs: 0

In [85]:
from sklearn.model_selection import train_test_split

# Assign a common group ID to each matched pair
model_df["group_id"] = model_df["record_id"]

mask = model_df["target"] == 0

model_df.loc[mask, "group_id"] = (
    model_df.loc[mask, "matched_positive_record_id"]
)

# Get unique matched pairs
groups = model_df["group_id"].unique()

# Split groups, not individual rows
train_groups, val_groups = train_test_split(
    groups,
    test_size=0.20,
    random_state=42
)

# Create training and validation datasets
train_df = model_df[
    model_df["group_id"].isin(train_groups)
].copy()

val_df = model_df[
    model_df["group_id"].isin(val_groups)
].copy()

print("Training:", train_df.shape)
print("Validation:", val_df.shape)

Training: (154, 27)
Validation: (40, 27)

In [86]:
# Check class balance
print("Training target counts:")
print(train_df["target"].value_counts())

print("\nValidation target counts:")
print(val_df["target"].value_counts())

# Check that no matched pairs appear in both sets
overlap = set(train_df["group_id"]) & set(val_df["group_id"])

print("\nOverlapping groups:", len(overlap))

assert len(overlap) == 0
assert len(train_df) + len(val_df) == len(model_df)

Training target counts:
target
1    77
0    77
Name: count, dtype: int64

Validation target counts:
target
0    20
1    20
Name: count, dtype: int64

Overlapping groups: 0

In [87]:
train_df = train_df.drop(columns=["group_id"])
val_df = val_df.drop(columns=["group_id"])

train_df.to_csv(
    "data/processed/hab_train.csv",
    index=False
)

val_df.to_csv(
    "data/processed/hab_validation.csv",
    index=False
)

print("Training and validation datasets saved!")

Training and validation datasets saved!

In [88]:
!ls -lh data/processed/hab_train.csv
!ls -lh data/processed/hab_validation.csv

!git status

-rw-r--r-- 1 root root 45K Oct 27 15:22 data/processed/hab_train.csv
-rw-r--r-- 1 root root 12K Oct 27 15:22 data/processed/hab_validation.csv
On branch task3-data-splitting
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	data/processed/hab_train.csv
	data/processed/hab_validation.csv

nothing added to commit but untracked files present (use "git add" to track)

In [89]:
!git add data/processed/hab_train.csv
!git add data/processed/hab_validation.csv
!git status

On branch task3-data-splitting
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   data/processed/hab_train.csv
	new file:   data/processed/hab_validation.csv

In [90]:
!git commit -m "Create grouped training and validation datasets"

[task3-data-splitting 7242d51] Create grouped training and validation datasets
 2 files changed, 196 insertions(+)
 create mode 100644 data/processed/hab_train.csv
 create mode 100644 data/processed/hab_validation.csv

In [91]:
!git branch --show-current
!git remote -v

task3-data-splitting
origin	https://github.com/Break-Through-Tech/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems.git (fetch)
origin	https://github.com/Break-Through-Tech/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems.git (push)

In [92]:
from google.colab import userdata

token = userdata.get("GITHUB_TOKEN")

In [94]:
from google.colab import userdata
import subprocess
import os
import base64

token = userdata.get("GITHUB_TOKEN")

if not token:
    raise ValueError("GitHub token not found in Colab Secrets")

auth = base64.b64encode(
    f"x-access-token:{token}".encode()
).decode()

env = os.environ.copy()
env["GIT_CONFIG_COUNT"] = "1"
env["GIT_CONFIG_KEY_0"] = "http.extraheader"
env["GIT_CONFIG_VALUE_0"] = f"AUTHORIZATION: basic {auth}"

result = subprocess.run(
    ["git", "push", "-u", "origin", "HEAD"],
    env=env,
    capture_output=True,
    text=True
)

print("Exit code:", result.returncode)
print(result.stderr)

del token, auth, env

Exit code: 0
remote:
remote: Create a pull request for 'task3-data-splitting' on GitHub by visiting:
remote:      https://github.com/Break-Through-Tech/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/pull/new/task3-data-splitting
remote:
To https://github.com/Break-Through-Tech/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems.git
 * [new branch]      HEAD -> task3-data-splitting