In [111]:
from google.colab import userdata

!git config --global user.name "megiva"
!git config --global user.email "meghana.m.ivaturi@gmail.com"

token = userdata.get("GITHUB_TOKEN")

In [112]:
organization = 'Break-Through-Tech'
repo = 'Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems'

In [113]:
!git clone https://{token}@github.com/{organization}/{repo}

Cloning into 'Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems'...
remote: Enumerating objects: 180, done.
remote: Counting objects: 100% (180/180), done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 180 (delta 79), reused 99 (delta 30), pack-reused 0 (from 0)
Receiving objects: 100% (180/180), 3.96 MiB | 10.66 MiB/s, done.
Resolving deltas: 100% (79/79), done.

In [114]:
%ls
%pwd

Challenge-Project-Overview.md
copernicusmarine/
data/
Documentation.md
Getting-Started-for-Fellows.md
literature/
notebooks/
Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/
README.md
requirements.txt

'/content/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems'

In [115]:
%cd /content/{repo}

/content/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems

In [116]:
%pwd

'/content/Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems'

In [117]:
!git checkout -b task3-standardization

fatal: a branch named 'task3-standardization' already exists

In [118]:
!git branch

  main
* task3-standardization

In [119]:
import pandas as pd
df = pd.read_csv("data/raw/harmful_algae_events.csv")
df.head()

/tmp/ipykernel_731/4273240831.py:2: DtypeWarning: Columns (6,19,48,62) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/raw/harmful_algae_events.csv")

,Event ID,Event Name,Year,Country,Region,Status,Submitter,Created At,Updated At,Event Date,...,Advected Info,Stratification Info,Nutrients,Additional Env Info,Additional Harmful Effect Info,Additional Bloom Info,Management Decision,Economic Losses,References,Contacts
0,14822,NO-26-015,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-06-22,2026-06-22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Harvesting was locally banned. The public was ...,Unknown,NaN,Mona Ring Kleiven
1,14819,NO-26-012,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-06-22,2026-06-22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Harvesting was locally banned. The public was ...,Unknown,NaN,Mona Ring Kleiven
2,14810,NO-26-003,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-05-18,2026-05-18,NaN,...,0-3 m,NaN,NaN,NaN,NaN,NaN,Fish farms warned,NaN,NaN,Mona Ring Kleiven
3,14821,NO-26-014,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-06-22,2026-06-22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Harvesting was locally banned. The public was ...,Unknown,NaN,Mona Ring Kleiven
4,14812,NO-26-005,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-06-22,2026-06-22,2026-04-06,...,NaN,NaN,NaN,NaN,NaN,NaN,Harvesting was locally banned. The public was ...,Unknown,NaN,Mona Ring Kleiven

In [120]:
df.shape

(14101, 85)

In [121]:
df.columns.tolist()

['Event ID',
 'Event Name',
 'Year',
 'Country',
 'Region',
 'Status',
 'Submitter',
 'Created At',
 'Updated At',
 'Event Date',
 'Start Date',
 'End Date',
 'Date Comments',
 'Quarantine Start',
 'Quarantine End',
 'Additional Date Info',
 'Latitude',
 'Longitude',
 'Location Description',
 'Original Grid Code',
 'Monitoring Grids',
 'Additional Location Info',
 'Monitoring Programme?',
 'Programme Name',
 'Occurred Before?',
 'Occurred Before Details',
 'Water Discoloration',
 'High Phytoplankton',
 'Seafood Toxin',
 'Mass Mortality',
 'Foam/Mucilage',
 'Freshwater',
 'Other Effect',
 'Other Effect Details',
 'Humans Affected',
 'Natural Fish Affected',
 'Aquaculture Fish Affected',
 'Shellfish Affected',
 'Birds Affected',
 'Marine Mammals Affected',
 'Plankton Affected',
 'Benthic Life Affected',
 'Seaweed Affected',
 'Other Terrestrial Affected',
 'Impact Comments',
 'Terrestrial Comments',
 'Toxin Detected?',
 'Toxicity Range',
 'Unexplained Toxicity',
 'Toxicity Comments',
 'Transvectors',
 'Causative Species',
 'Causative Species Details',
 'Associated Species',
 'Associated Species Details',
 'Syndromes',
 'Toxins Found',
 'Assay Species Tested',
 'Assay Toxins',
 'Assay Concentrations',
 'Assay Methods',
 'Chlorophyll Analysis',
 'Additional Algae Info',
 'Weather Conditions',
 'Wind Direction',
 'Wind Velocity',
 'Water Temp',
 'Salinity',
 'Oxygen Content',
 'Oxygen Saturation',
 'Turbidity',
 'Secchi Disc',
 'Current Velocity',
 'Advected?',
 'In Situ?',
 'Advected Info',
 'Stratification Info',
 'Nutrients',
 'Additional Env Info',
 'Additional Harmful Effect Info',
 'Additional Bloom Info',
 'Management Decision',
 'Economic Losses',
 'References',
 'Contacts']

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14101 entries, 0 to 14100
Data columns (total 85 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Event ID                        14101 non-null  int64
 1   Event Name                      14101 non-null  object
 2   Year                            14101 non-null  int64
 3   Country                         14101 non-null  object
 4   Region                          245 non-null    object
 5   Status                          14101 non-null  object
 6   Submitter                       17 non-null     object
 7   Created At                      10819 non-null  object
 8   Updated At                      3188 non-null   object
 9   Event Date                      7761 non-null   object
 10  Start Date                      3856 non-null   object
 11  End Date                        3403 non-null   object
 12  Date Comments                   1969 non-null   object
 13  Quarantine Start                2593 non-null   object
 14  Quarantine End                  2280 non-null   object
 15  Additional Date Info            1974 non-null   object
 16  Latitude                        14044 non-null  float64
 17  Longitude                       14044 non-null  float64
 18  Location Description            13410 non-null  object
 19  Original Grid Code              929 non-null    object
 20  Monitoring Grids                13706 non-null  object
 21  Additional Location Info        2599 non-null   object
 22  Monitoring Programme?           14101 non-null  object
 23  Programme Name                  11010 non-null  object
 24  Occurred Before?                14084 non-null  object
 25  Occurred Before Details         2327 non-null   object
 26  Water Discoloration             14101 non-null  object
 27  High Phytoplankton              14101 non-null  object
 28  Seafood Toxin                   14101 non-null  object
 29  Mass Mortality                  14101 non-null  object
 30  Foam/Mucilage                   14101 non-null  object
 31  Freshwater                      14101 non-null  object
 32  Other Effect                    14101 non-null  object
 33  Other Effect Details            186 non-null    object
 34  Humans Affected                 14101 non-null  object
 35  Natural Fish Affected           14101 non-null  object
 36  Aquaculture Fish Affected       14101 non-null  object
 37  Shellfish Affected              14101 non-null  object
 38  Birds Affected                  14101 non-null  object
 39  Marine Mammals Affected         14101 non-null  object
 40  Plankton Affected               14101 non-null  object
 41  Benthic Life Affected           14101 non-null  object
 42  Seaweed Affected                14101 non-null  object
 43  Other Terrestrial Affected      14101 non-null  object
 44  Impact Comments                 878 non-null    object
 45  Terrestrial Comments            0 non-null      float64
 46  Toxin Detected?                 14101 non-null  object
 47  Toxicity Range                  4472 non-null   object
 48  Unexplained Toxicity            3392 non-null   object
 49  Toxicity Comments               210 non-null    object
 50  Transvectors                    5260 non-null   object
 51  Causative Species               7859 non-null   object
 52  Causative Species Details       7859 non-null   object
 53  Associated Species              952 non-null    object
 54  Associated Species Details      952 non-null    object
 55  Syndromes                       11587 non-null  object
 56  Toxins Found                    0 non-null      float64
 57  Assay Species Tested            3455 non-null   object
 58  Assay Toxins                    2249 non-null   object
 59  Assay Concentrations            1351 non-null   object
 60  Assay Methods                   3285 non-null   object
 61  Chlorophyll Analysis            1 non-null      float64
 62  Additional Algae Info           3 non-null      object
 63  Weather Conditions              267 non-null    object
 64  Wind Direction                  14081 non-null  object
 65  Wind Velocity                   124 non-null    object
 66  Water Temp                      665 non-null    object
 67  Salinity                        506 non-null    object
 68  Oxygen Content                  168 non-null    object
 69  Oxygen Saturation               79 non-null     object
 70  Turbidity                       87 non-null     object
 71  Secchi Disc                     143 non-null    object
 72  Current Velocity                1855 non-null   object
 73  Advected?                       14082 non-null  object
 74  In Situ?                        14082 non-null  object
 75  Advected Info                   835 non-null    object
 76  Stratification Info             1758 non-null   float64
 77  Nutrients                       0 non-null      float64
 78  Additional Env Info             596 non-null    object
 79  Additional Harmful Effect Info  1764 non-null   object
 80  Additional Bloom Info           169 non-null    object
 81  Management Decision             3949 non-null   object
 82  Economic Losses                 815 non-null    object
 83  References                      2154 non-null   object
 84  Contacts                        13801 non-null  object
dtypes: float64(7), int64(2), object(76)
memory usage: 9.1+ MB

# Task 3: Standardize Categorical Variables and Numerical Features

This notebook standardizes the harmful algae event dataset so that
categorical values, dates, coordinates, and numerical measurements use
consistent formats for later feature engineering and modeling.

In [123]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/raw/harmful_algae_events.csv", low_memory=False)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (14101, 85)

,Event ID,Event Name,Year,Country,Region,Status,Submitter,Created At,Updated At,Event Date,...,Advected Info,Stratification Info,Nutrients,Additional Env Info,Additional Harmful Effect Info,Additional Bloom Info,Management Decision,Economic Losses,References,Contacts
0,14822,NO-26-015,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-06-22,2026-06-22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Harvesting was locally banned. The public was ...,Unknown,NaN,Mona Ring Kleiven
1,14819,NO-26-012,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-06-22,2026-06-22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Harvesting was locally banned. The public was ...,Unknown,NaN,Mona Ring Kleiven
2,14810,NO-26-003,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-05-18,2026-05-18,NaN,...,0-3 m,NaN,NaN,NaN,NaN,NaN,Fish farms warned,NaN,NaN,Mona Ring Kleiven
3,14821,NO-26-014,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-06-22,2026-06-22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Harvesting was locally banned. The public was ...,Unknown,NaN,Mona Ring Kleiven
4,14812,NO-26-005,2026,NORWAY,Region 12 (EUR),Submitted,mona.ring.kleiven@hi.no,2026-06-22,2026-06-22,2026-04-06,...,NaN,NaN,NaN,NaN,NaN,NaN,Harvesting was locally banned. The public was ...,Unknown,NaN,Mona Ring Kleiven

In [124]:
date_cols = [
    "Created At",
    "Updated At",
    "Event Date",
    "Start Date",
    "End Date",
    "Quarantine Start",
    "Quarantine End"
]

df[date_cols].head(10)

,Created At,Updated At,Event Date,Start Date,End Date,Quarantine Start,Quarantine End
0,2026-06-22,2026-06-22,NaN,2026-05-04,2026-06-01,NaN,NaN
1,2026-06-22,2026-06-22,NaN,2026-04-20,2026-06-01,NaN,NaN
2,2026-05-18,2026-05-18,NaN,2026-04-20,2026-05-04,NaN,NaN
3,2026-06-22,2026-06-22,NaN,2026-04-20,2026-06-15,NaN,NaN
4,2026-06-22,2026-06-22,2026-04-06,NaN,NaN,2026-04-20,2026-06-15
5,2026-06-22,2026-06-22,NaN,2026-04-06,2026-05-18,NaN,NaN
6,2026-06-22,2026-06-22,NaN,2026-05-25,2026-06-08,NaN,NaN
7,2026-06-22,2026-06-22,2026-04-20,2026-04-20,2026-05-18,NaN,NaN
8,2026-06-22,2026-06-22,NaN,2026-04-20,2026-06-15,NaN,NaN
9,2026-05-05,2026-05-05,NaN,2026-03-17,2026-04-01,NaN,NaN

In [125]:
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [126]:
df[date_cols].dtypes

Created At          datetime64[ns]
Updated At          datetime64[ns]
Event Date          datetime64[ns]
Start Date          datetime64[ns]
End Date            datetime64[ns]
Quarantine Start    datetime64[ns]
Quarantine End      datetime64[ns]
dtype: object

In [127]:
for col in date_cols:
    print(col)
    print("Non-null:", df[col].notna().sum())
    print()

Created At
Non-null: 10819

Updated At
Non-null: 3188

Event Date
Non-null: 7761

Start Date
Non-null: 3856

End Date
Non-null: 3403

Quarantine Start
Non-null: 2593

Quarantine End
Non-null: 2280

In [128]:
categorical_cols = [
    "Country",
    "Region",
    "Status",
    "Monitoring Programme?",
    "Occurred Before?",
    "Water Discoloration",
    "High Phytoplankton",
    "Seafood Toxin",
    "Mass Mortality",
    "Foam/Mucilage",
    "Freshwater",
    "Other Effect",
    "Toxin Detected?",
    "Advected?",
    "In Situ?"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Country ---
Country
FRENCH POLYNESIA    3968
PHILIPPINES         1311
FRANCE              1076
UNITED STATES       1020
PORTUGAL             788
                    ...
GHANA                  1
HONG KONG              1
LITHUANIA              1
KUWAIT                 1
LUXEMBOURG             1
Name: count, Length: 106, dtype: int64

--- Region ---
Region
NaN                        13856
Region 12 (EUR)               63
Region 11 (MED)               45
Region 7 (NAS)                27
Region 9 (Benguela)           16
Region 2 (CCA)                15
HANA                          14
FANSA                         13
ANCA                          12
Region 3 (SAM)                11
Region 6 (SEA)                 8
Region 8 (Indian Ocean)        7
ICES: NEA                      6
Region 5 (ANZ)                 4
PICES: NWP                     3
PICES: NEP                     1
Name: count, dtype: int64

--- Status ---
Status
Approved     14084
Submitted       17
Name: count, dtype: int64

--- Monitoring Programme? ---
Monitoring Programme?
Yes    12133
No      1968
Name: count, dtype: int64

--- Occurred Before? ---
Occurred Before?
No     14084
NaN       17
Name: count, dtype: int64

--- Water Discoloration ---
Water Discoloration
No     12436
Yes     1665
Name: count, dtype: int64

--- High Phytoplankton ---
High Phytoplankton
No     10787
Yes     3314
Name: count, dtype: int64

--- Seafood Toxin ---
Seafood Toxin
Yes    10351
No      3750
Name: count, dtype: int64

--- Mass Mortality ---
Mass Mortality
No     13251
Yes      850
Name: count, dtype: int64

--- Foam/Mucilage ---
Foam/Mucilage
No     13996
Yes      105
Name: count, dtype: int64

--- Freshwater ---
Freshwater
No     13634
Yes      467
Name: count, dtype: int64

--- Other Effect ---
Other Effect
No     13928
Yes      173
Name: count, dtype: int64

--- Toxin Detected? ---
Toxin Detected?
No     7696
Yes    6405
Name: count, dtype: int64

--- Advected? ---
Advected?
No     13504
Yes      578
NaN       19
Name: count, dtype: int64

--- In Situ? ---
In Situ?
No     13063
Yes     1019
NaN       19
Name: count, dtype: int64

In [129]:
print("Unique causative species:", df["Causative Species"].nunique())

df["Causative Species"].value_counts(dropna=False).head(30)

Unique causative species: 911

Causative Species
NaN                                                          6242
Pyrodinium bahamense                                          806
Dinophysis acuminata                                          620
Dinophysis spp.                                               548
Microcystis spp.                                              385
Alexandrium spp.                                              337
Pseudo-nitzschia spp.                                         308
Pyrodinium bahamense var. compressum                          250
Alexandrium catenella                                         221
Gymnodinium catenatum                                         189
Dinophysis acuta                                              160
Cochlodinium polykrikoides                                    112
Alexandrium tamarense                                         107
Heterosigma akashiwo                                          103
Pseudo-nitzschia australis                                     97
Alexandrium sp.                                                95
Karenia mikimotoi                                              88
Skeletonema costatum                                           86
Nodularia spumigena                                            73
Noctiluca scintillans                                          72
Alexandrium minutum                                            71
Karenia brevis                                                 66
Gymnodinium catenatum Graham 1943                              62
Dinophysis sp.                                                 58
Prorocentrum minimum                                           56
Aureococcus anophagefferens                                    47
Alexandrium fundyense                                          44
Noctiluca scintillans (Macartney) Kofoid et Swezy 1921         44
Cylindrospermopsis raciborskii Seenaya et Subba Raju 1972      41
Gymnodinium sp.                                                38
Name: count, dtype: int64

In [130]:
print("Unique associated species:", df["Associated Species"].nunique())

df["Associated Species"].value_counts(dropna=False).head(30)

Unique associated species: 404

Associated Species
NaN                                                          13149
Cylindrospermopsis raciborskii Seenaya et Subba Raju 1972      117
Dinophysis acuminata                                            43
Dinophysis acuta                                                36
Alexandrium spp.                                                33
Aphanizomenon flos-aquae                                        26
Pseudo-nitzschia spp.                                           23
Alexandrium tamarense                                           17
Nodularia spumigena                                             15
Karenia mikimotoi                                               14
Skeletonema costatum                                            12
Dinophysis norvegica                                            12
Pseudo-nitzschia calliantha                                     11
Gymnodinium sp.                                                 10
Aphanizomenon flos-aquae; Dolichospermum spp.                   10
Dinophysis caudata                                               9
Alexandrium ostenfeldii                                          8
Prorocentrum micans                                              8
Heterocapsa triquetra                                            8
Heterosigma akashiwo                                             7
Prorocentrum minimum                                             7
Cochlodinium polykrikoides                                       7
Dinophysis spp.                                                  7
Anabaena spp.                                                    6
Skeletonema costatum (Greville) Cleve 1878                       6
Karenia papilionacea                                             6
Pyrodinium bahamense                                             6
Dinophysis sacculus                                              5
Chaetoceros convolutus                                           5
Dictyocha speculum                                               5
Name: count, dtype: int64

In [131]:
categorical_cols = [
    "Country",
    "Region",
    "Status",
    "Monitoring Programme?",
    "Occurred Before?",
    "Water Discoloration",
    "High Phytoplankton",
    "Seafood Toxin",
    "Mass Mortality",
    "Foam/Mucilage",
    "Freshwater",
    "Other Effect",
    "Toxin Detected?",
    "Advected?",
    "In Situ?"
]

for col in categorical_cols:
    df[col] = df[col].str.strip()

In [132]:
df["Country"] = df["Country"].str.title()

In [133]:
df["Country"].value_counts().head(20)

Country
French Polynesia      3968
Philippines           1311
France                1076
United States         1020
Portugal               788
Spain                  746
Canada                 739
Norway                 694
Japan                  542
United Kingdom         359
Ireland                304
Mexico                 222
China                  216
Sweden                 183
Australia              123
Slovenia               122
Korea, Republic Of     121
Turkey                  93
Poland                  92
Chile                   86
Name: count, dtype: int64

In [134]:
species_cols = [
    "Causative Species",
    "Associated Species"
]

for col in species_cols:
    df[col] = (
        df[col]
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

In [135]:
print("Countries:", df["Country"].nunique())
print("Causative species:", df["Causative Species"].nunique())
print("Associated species:", df["Associated Species"].nunique())

print("\nCountry examples:")
print(df["Country"].value_counts().head(10))

print("\nYes/No check:")
for col in [
    "Monitoring Programme?",
    "Water Discoloration",
    "High Phytoplankton",
    "Seafood Toxin",
    "Mass Mortality",
    "Toxin Detected?",
    "Advected?",
    "In Situ?"
]:
    print(col, df[col].dropna().unique())

Countries: 106
Causative species: 911
Associated species: 404

Country examples:
Country
French Polynesia    3968
Philippines         1311
France              1076
United States       1020
Portugal             788
Spain                746
Canada               739
Norway               694
Japan                542
United Kingdom       359
Name: count, dtype: int64

Yes/No check:
Monitoring Programme? ['No' 'Yes']
Water Discoloration ['No' 'Yes']
High Phytoplankton ['Yes' 'No']
Seafood Toxin ['No' 'Yes']
Mass Mortality ['No' 'Yes']
Toxin Detected? ['Yes' 'No']
Advected? ['No' 'Yes']
In Situ? ['No' 'Yes']

In [136]:
invalid_coords = df[
    (~df["Latitude"].between(-90, 90)) |
    (~df["Longitude"].between(-180, 180))
]

invalid_coords[
    ["Event ID", "Country", "Location Description", "Latitude", "Longitude"]
]

,Event ID,Country,Location Description,Latitude,Longitude
194,14210,Australia,Aldinga Beach,NaN,NaN
196,14209,Australia,Bruny Island,NaN,NaN
951,13594,Guatemala,"Madre Vieja, Tiquisate",NaN,NaN
952,13595,Guatemala,"El Semillero, Tiquisate",NaN,NaN
961,14411,Mexico,Península de Yucatán,21.7187,-808.8684
1166,13430,Cuba,San Miguel del Padrón,NaN,NaN
1450,14367,Turkey,Sea of Marmara,NaN,NaN
1451,14365,Turkey,Sea of Marmara,NaN,NaN
1452,14363,Turkey,Sea of Marmara,NaN,NaN
1453,14364,Turkey,Sea of Marmara,NaN,NaN
1454,14366,Turkey,Sea of Marmara,NaN,NaN
4237,7302,Mexico,Puerto Dzilam,21.7187,-808.8684
4240,7304,Mexico,Puerto Dzilam,21.7187,-808.8684
4871,9040,United Kingdom,Isle of Man,NaN,NaN
5212,7556,Indonesia,Maninjau,NaN,NaN
5305,9032,Portugal,Northeastern Atlantic Ocean,NaN,NaN
5854,9033,Portugal,Central-eastern Atlantic,NaN,NaN
6307,7266,Mexico,Holbox,21.7187,-808.8684
6318,7264,Mexico,Rio Lagartos,21.7187,-808.8684
6831,7578,Kenya,Nakuru oxidation ponds,NaN,NaN
6972,5633,Tunisia,Gulf of Gabes,NaN,NaN
7629,5631,Tunisia,Gulf of Gabes,NaN,NaN
7630,5632,Tunisia,Gulf of Gabes,NaN,NaN
7631,7792,Uganda,Murchison Bay,NaN,NaN
8083,7335,Mexico,Río Lagos,21.7187,-808.8684
8088,7255,Mexico,Puerto Progreso,21.7187,-808.8684
8136,9031,Portugal,Central-eastern Atlantic,NaN,NaN
8598,1800,Japan,NaN,NaN,NaN
8600,1799,Japan,NaN,NaN,NaN
8732,5621,Tunisia,Lagoulette and Rodes harbour,NaN,NaN
8738,7788,Uganda,Lake Mburo,NaN,NaN
8739,7789,Uganda,Lake Saka,NaN,NaN
10075,10278,Oman,Undetermined locatio,NaN,NaN
10077,10277,Oman,NaN,NaN,NaN
10164,7796,Uganda,Napoleon,NaN,NaN
10165,7795,Uganda,Lake Edward,NaN,NaN
10166,7794,Uganda,Lake George,NaN,NaN
10382,7187,Mexico,Puerto Dzilam,21.7187,-808.8684
10462,9041,United Kingdom,NaN,NaN,NaN
11060,7582,Kenya,Lake Bogoria,NaN,NaN
11061,7580,Kenya,Lake Baringo,NaN,NaN
11062,7583,Kenya,Lake Simbi,NaN,NaN
11063,7581,Kenya,Lake Sonachi,NaN,NaN
11064,7837,Kenya,Lake Elmenteita,NaN,NaN
11065,7579,Kenya,Nyanza Gulf of Lake Victoria,NaN,NaN
12370,117,Finland,Gulf of Finland,NaN,NaN
12416,14325,Indonesia,Pieh Island,NaN,NaN
12422,1082,Ireland,NaN,NaN,NaN
12550,7565,Italy,Bidighinzu Reservoir,NaN,NaN
12880,1723,France,NaN,NaN,NaN
12881,1717,France,NaN,NaN,NaN
12882,312,France,NaN,NaN,NaN
12883,1721,France,NaN,NaN,NaN
12884,1718,France,NaN,NaN,NaN
12885,1722,France,NaN,NaN,NaN
12886,1720,France,NaN,NaN,NaN
12887,1102,France,NaN,NaN,NaN
12888,1719,France,NaN,NaN,NaN
12889,1103,France,NaN,NaN,NaN
12890,1407,France,NaN,NaN,NaN
12891,1408,France,NaN,NaN,NaN
13057,1091,Denmark,NaN,NaN,NaN
13059,114,Finland,Gulf of Finland and Bothnian Sea.,NaN,NaN
13397,6296,Mexico,Holbox,21.7187,-808.8684
14065,9091,India,Laccadives,NaN,NaN
14068,9090,India,Waltair,NaN,NaN

In [137]:
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")

In [138]:
df["Valid Coordinates"] = (
    df["Latitude"].between(-90, 90) &
    df["Longitude"].between(-180, 180)
)

In [139]:
df["Valid Coordinates"].value_counts()

Valid Coordinates
True     14035
False       66
Name: count, dtype: int64

In [140]:
measurement_cols = [
    "Water Temp",
    "Salinity",
    "Oxygen Content",
    "Oxygen Saturation",
    "Turbidity",
    "Secchi Disc",
    "Current Velocity",
    "Wind Velocity"
]

for col in measurement_cols:
    print(f"\n--- {col} ---")
    print(df[col].dropna().head(20).tolist())

--- Water Temp ---
['25', '24°C to 31°C', '30-47oC', '24°C to 31°C', '24°C to 31°C', '24°C to 31°C', '24°C to 31°C', '24°C to 31°C', '24°C to 31°C', '24°C to 31°C', '24°C to 31°C', '21', '28.3', '27.1', '21.5', '21.5', '21.3', '18.3', '15.3', '28.5']

--- Salinity ---
['30', '23', '1 PSU', '4.6', '30', '30', '29', '30', '6,5', '34.7-35.1', '32.1', '30.2', '18.9', '37.1', '27', '7', '32.3', '34.7-35.4', '35.2-35.2', '34.9-35.2']

--- Oxygen Content ---
['28', 'oxygen depletion', '8', '4.28', '6.3', '9.97 mg L-1', '9 mg L-1', '11.2', '0.1', '6.88', '6.1', '8.32', '0', '5.8', 'No', '1.47 - 10.55', '3.00', '10.9 mg/L', '18.42', '15.13']

--- Oxygen Saturation ---
['29', '115', '77.3', '15% at 5m', '0', 'No', '3.95', '137.6', '229.1', '241.3', '102.3', '128', 'No', '132 @ 0 m; 120 @ 5 m; 102 @ 10 m', '66', '119.36', '>200', '112 at 1m', '7.4', '43.5']

--- Turbidity ---
['27', '0.9', '6', '0,1', '1,2', '1', '4,31', '1,6', '3,3', '15,3', '4,8', '2', 'No', '24.0', '0.82', 'No', '9,67-19,46', '13.0', '32.6', '9.7']

--- Secchi Disc ---
['26', '0.05', '7', '14', '15', '13', '19', '11', '8', '2.0 - 2.3', '1', '5', '10.5', '1.2', 'No', '0.5cm', '.4', '0.5', '0.3', 'No']

--- Current Velocity ---
['32', 'n.a.', 'No', 'No', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

--- Wind Velocity ---
['31', '1', '2', '2-4', '3', '5', '13.9 m/s', '1.9 m/s', '5.83 m/s', '3m/seg', 'No', '1.74 m/s', 'No', '3m/s', '10 knots', '0.4 - 5.0 ms-1', '2.1 - 6.4 (m3 s &#87', 'light', '6 knots', '3']

In [141]:
measurement_cols = [
    "Water Temp",
    "Salinity",
    "Oxygen Content",
    "Oxygen Saturation",
    "Turbidity",
    "Secchi Disc",
    "Current Velocity",
    "Wind Velocity"
]

for col in measurement_cols:
    df[col] = (
        df[col]
        .astype("string")
        .str.strip()
        .str.replace(",", ".", regex=False)
    )

In [142]:
import re
import numpy as np

def parse_temperature(value):
    if pd.isna(value):
        return np.nan

    text = str(value).strip().lower()

    # Extract numbers without treating range hyphens as negative signs
    numbers = re.findall(r"\d+(?:\.\d+)?", text)

    if len(numbers) == 0:
        return np.nan

    numbers = [float(x) for x in numbers]

    # Single temperature
    if len(numbers) == 1:
        return numbers[0]

    # Temperature range -> midpoint
    if len(numbers) == 2:
        return sum(numbers) / 2

    return np.nan

In [143]:
df["Water Temp Celsius"] = df["Water Temp"].apply(parse_temperature)

In [144]:
df[
    ["Water Temp", "Water Temp Celsius"]
].dropna().head(30)

        Water Temp  Water Temp Celsius
30              25                25.0
132   24°C to 31°C                27.5
192        30-47oC                38.5
337   24°C to 31°C                27.5
362   24°C to 31°C                27.5
366   24°C to 31°C                27.5
367   24°C to 31°C                27.5
383   24°C to 31°C                27.5
406   24°C to 31°C                27.5
408   24°C to 31°C                27.5
413   24°C to 31°C                27.5
518             21                21.0
573           28.3                28.3
574           27.1                27.1
688           21.5                21.5
689           21.5                21.5
691           21.3                21.3
808           18.3                18.3
809           15.3                15.3
810           28.5                28.5
843           30.6                30.6
965             19                19.0
1038            23                23.0
1077     13.3-15.1                14.2
1136            18                18.0
1137          21.8                21.8
1138          16.3                16.3
1139          25.1                25.1
1160          26.1                26.1
1177            12                12.0

In [145]:
df["Water Temp Celsius"].describe()

count    642.000000
mean      19.736503
std        6.604735
min        0.000000
25%       15.400000
50%       19.625000
75%       24.600000
max       38.500000
Name: Water Temp Celsius, dtype: float64

In [146]:
df.loc[[192, 1077], ["Water Temp", "Water Temp Celsius"]]

     Water Temp  Water Temp Celsius
192     30-47oC                38.5
1077  13.3-15.1                14.2

In [147]:
df["Water Temp Celsius"].describe()

count    642.000000
mean      19.736503
std        6.604735
min        0.000000
25%       15.400000
50%       19.625000
75%       24.600000
max       38.500000
Name: Water Temp Celsius, dtype: float64

In [148]:
df[
    ["Event ID", "Country", "Water Temp", "Water Temp Celsius"]
].sort_values("Water Temp Celsius").head(10)

       Event ID             Country       Water Temp  Water Temp Celsius
5772       4911  Korea, Republic Of                0                0.00
5773       4910  Korea, Republic Of                0                0.00
5326       4118  Russian Federation             -1.8                1.80
11112      1381              Norway              1-3                2.00
13728      2573              Canada         8 - -1.3                4.65
10101      1993  Russian Federation                5                5.00
3597       6005               Chile              5.7                5.70
9310       2315              Canada  Min.3.5 Max.8.0                5.75
3599       6004               Chile              5.8                5.80
7062       6002               Chile              5.9                5.90

In [149]:
df[
    ["Event ID", "Country", "Water Temp", "Water Temp Celsius"]
].sort_values("Water Temp Celsius", ascending=False).head(10)

      Event ID      Country Water Temp  Water Temp Celsius
192      14344    Australia    30-47oC                38.5
4034      4946     Colombia       35.4                35.4
3619      5739     Colombia       34.7                34.7
4033      4948     Colombia       33.8                33.8
4032      5744     Colombia       33.8                33.8
4040      4945         Cuba       33.6                33.6
4031      5742     Colombia       33.5                33.5
9601      6488  Philippines      31-36                33.5
4462      4958     Colombia       32.9                32.9
3616      5706     Colombia       32.6                32.6

In [150]:
import re
import numpy as np

def parse_salinity(value):
    if pd.isna(value):
        return np.nan

    text = str(value).strip().lower()

    # Match numbers including decimals such as .04
    numbers = re.findall(r"(?:\d+\.\d+|\.\d+|\d+)", text)

    if len(numbers) == 0:
        return np.nan

    numbers = [float(x) for x in numbers]

    # If "at Xm" appears, the first number is the salinity
    if re.search(r"\bat\s*\d*\.?\d+\s*m\b", text):
        return numbers[0]

    # One number = straightforward value
    if len(numbers) == 1:
        return numbers[0]

    # Only treat two numbers as a range if a range separator is present
    if re.search(r"\d\s*(?:-|–|to)\s*\d", text):
        return (numbers[0] + numbers[1]) / 2

    # Too ambiguous to safely interpret
    return np.nan

In [151]:
df["Salinity Standardized"] = df["Salinity"].apply(parse_salinity)

In [152]:
df[
    ["Salinity", "Salinity Standardized"]
].dropna().head(30)

          Salinity  Salinity Standardized
30              30                  30.00
518             23                  23.00
573          1 PSU                   1.00
574            4.6                   4.60
688             30                  30.00
689             30                  30.00
691             29                  29.00
965             30                  30.00
1038           6.5                   6.50
1077     34.7-35.1                  34.90
1136          32.1                  32.10
1137          30.2                  30.20
1138          18.9                  18.90
1160          37.1                  37.10
1281            27                  27.00
1401             7                   7.00
1422          32.3                  32.30
1424     34.7-35.4                  35.05
1425     35.2-35.2                  35.20
1426     34.9-35.2                  35.05
1432     35.1-35.3                  35.20
1438     34.8-35.5                  35.15
1506          30.5                  30.50
1507          29.8                  29.80
1508            25                  25.00
1509          19.9                  19.90
1516  32 psu at 6m                  32.00
1535            29                  29.00
1536          33.5                  33.50
1537         34.33                  34.33

In [153]:
df["Salinity Standardized"].describe()

count    485.000000
mean      27.655766
std        9.832549
min        0.040000
25%       24.300000
50%       31.300000
75%       34.710000
max       50.900000
Name: Salinity Standardized, dtype: float64

In [154]:
df[
    ["Event ID", "Country", "Salinity", "Salinity Standardized"]
].sort_values("Salinity Standardized").head(10)

       Event ID        Country Salinity  Salinity Standardized
3541       6550  United States      .04                   0.04
11204      1427  United States      0.3                   0.30
573       14069        Ecuador    1 PSU                   1.00
11822      1165    Netherlands     1.07                   1.07
11816      1324         Latvia      3.8                   3.80
11068      1485         Latvia      4.5                   4.50
11069      1481         Latvia      4.5                   4.50
574       14376          Egypt      4.6                   4.60
10041      1745         Latvia      4.6                   4.60
11817      1158         Latvia     4.63                   4.63

In [155]:
df[
    ["Event ID", "Country", "Salinity", "Salinity Standardized"]
].sort_values("Salinity Standardized", ascending=False).head(10)

      Event ID             Country Salinity  Salinity Standardized
3616      5706            Colombia     50.9                   50.9
5383      4324       United States     42.0                   42.0
5957      4176       United States     41.6                   41.6
3803      7183               India       40                   40.0
7016      4949           Venezuela       40                   40.0
8263      5737               Egypt     39.6                   39.6
3619      5739            Colombia     39.6                   39.6
8840      5745               Egypt     39.1                   39.1
4044      4960  Dominican Republic       39                   39.0
8769      2025       United States     38.7                   38.7

In [156]:
df.loc[[1516, 3541], ["Salinity", "Salinity Standardized"]]

          Salinity  Salinity Standardized
1516  32 psu at 6m                  32.00
3541           .04                   0.04

In [157]:
df["Salinity Standardized"].describe()

count    485.000000
mean      27.655766
std        9.832549
min        0.040000
25%       24.300000
50%       31.300000
75%       34.710000
max       50.900000
Name: Salinity Standardized, dtype: float64

In [158]:
pd.set_option("display.max_rows", 200)

df["Oxygen Content"].value_counts(dropna=False).head(100)

Oxygen Content
<NA>                                                13933
6                                                       3
6.3                                                     2
7                                                       2
No                                                      2
2.1-11.2                                                2
7.9                                                     2
6.7                                                     2
7.7                                                     2
7.1                                                     2
5.84                                                    2
5.03                                                    2
28                                                      1
8.32                                                    1
6.1                                                     1
5.8                                                     1
0                                                       1
3.00                                                    1
10.9 mg/L                                               1
18.42                                                   1
1.47 - 10.55                                            1
4.28                                                    1
9.97 mg L-1                                             1
9 mg L-1                                                1
11.2                                                    1
0.1                                                     1
6.88                                                    1
8                                                       1
oxygen depletion                                        1
21.6 mg/l                                               1
4.96                                                    1
12.1 @ 0 m; 11.1 @ 5m; 10.0 @ 10 m                      1
< 0.06                                                  1
6.53                                                    1
9.89                                                    1
15.6                                                    1
15.13                                                   1
7.2                                                     1
5.12                                                    1
9.0 - 9.3                                               1
6.5                                                     1
9.3                                                     1
4.75-6.86                                               1
6.3-8                                                   1
8.19                                                    1
6.96 at 1m                                              1
8.3@1m.8@5m.6.3@10m                                     1
10.7@1m. 11.2@5m. 11.0@10m                              1
2.15                                                    1
6-8                                                     1
6.44                                                    1
8.8 (mg/L)                                              1
10.2                                                    1
4.60 - 8.6                                              1
8.8                                                     1
6.212@1m                                                1
6.95                                                    1
6.1 (mg/L)                                              1
4.37                                                    1
3.47                                                    1
10.5                                                    1
2.5-9.9                                                 1
7.53                                                    1
6.8                                                     1
6.94                                                    1
6.22                                                    1
7.4                                                     1
12.16                                                   1
5.8mg/L-8.7 mg/L                                        1
6.6 @1m                                                 1
8.1mg/L-9.5 mg/L                                        1
6.67@4m                                                 1
6-11.6mg/L                                              1
6.02                                                    1
9.7                                                     1
7.458                                                   1
7.24                                                    1
3.48 - 7.01                                             1
6.96                                                    1
6.6                                                     1
6.2                                                     1
7.5                                                     1
6.3 mg L-1                                              1
9.4mg/L@1m. 8.9mg/L@6m. 7.8mg/L@10m                     1
8.4mg/L@1m. 5.7mg/L@5m. 4.6mg/L@10m                     1
9.7mg/L@0m. 11.4mg/L@3m. 8.2mg/L@6m. 6.7mg/L@12m        1
8.23 mg/l                                               1
6.9                                                     1
15.34                                                   1
5.35                                                    1
6.85                                                    1
3.32                                                    1
10.3                                                    1
0 -10.3                                                 1
7.9 mg/L                                                1
6.68 mg/L                                               1
11.68                                                   1
8.22                                                    1
7.10                                                    1
7.6                                                     1
Name: count, dtype: Int64

In [159]:
df["Oxygen Content"].dropna().unique()

<StringArray>
[                                '28',                   'oxygen depletion',
                                  '8',                               '4.28',
                                '6.3',                        '9.97 mg L-1',
                           '9 mg L-1',                               '11.2',
                                '0.1',                               '6.88',
 ...
                               '<0.5',                              '0.002',
                         '110.2-128.',                               '5.04',
 'surf: 3.19-5.40; bottom: 0.45-3.86',                        '1.09 - 7.36',
                        '3.30 - 9.97',                              '11.77',
                        '5.32 - 6.90',                            '2.4-7.3']
Length: 156, dtype: string

In [160]:
import re
import numpy as np

def parse_oxygen(value):
    if pd.isna(value):
        return np.nan

    text = str(value).strip().lower()

    # Non-numeric descriptions
    if text in ["no", "oxygen depletion", "n.a.", "na"]:
        return np.nan

    # Remove mg/L-style units
    cleaned = re.sub(r"mg\s*/?\s*l(?:-1)?", "", text)
    cleaned = cleaned.strip()

    # Single numeric value
    if re.fullmatch(r"<?\s*(?:\d+\.\d+|\.\d+|\d+)", cleaned):
        numbers = re.findall(r"(?:\d+\.\d+|\.\d+|\d+)", cleaned)
        return float(numbers[0])

    # Simple range such as 1.47 - 10.55 or 6-8
    range_match = re.fullmatch(
        r"\s*(\d*\.?\d+)\s*-\s*(\d*\.?\d+)\s*",
        cleaned
    )

    if range_match:
        low = float(range_match.group(1))
        high = float(range_match.group(2))
        return (low + high) / 2

    # Everything more complicated stays missing
    return np.nan

In [161]:
df["Oxygen Content Standardized"] = (
    df["Oxygen Content"].apply(parse_oxygen)
)

In [162]:
print(
    "Original oxygen records:",
    df["Oxygen Content"].notna().sum()
)

print(
    "Standardized oxygen records:",
    df["Oxygen Content Standardized"].notna().sum()
)

Original oxygen records: 168
Standardized oxygen records: 132

In [163]:
df["Oxygen Content Standardized"].describe()

count    132.000000
mean       7.236705
std        3.573295
min        0.000000
25%        5.787500
50%        6.700000
75%        8.222500
max       28.000000
Name: Oxygen Content Standardized, dtype: float64

In [164]:
df[
    [
        "Event ID",
        "Country",
        "Oxygen Content",
        "Oxygen Content Standardized"
    ]
].sort_values(
    "Oxygen Content Standardized",
    ascending=False
).head(15)

       Event ID        Country Oxygen Content  Oxygen Content Standardized
30        14541       Colombia             28                        28.00
4464       4951           Cuba      21.6 mg/l                        21.60
3971       5456  United States          18.42                        18.42
3981       5462  United States           15.6                        15.60
9230       2946          Spain          15.34                        15.34
3979       5461  United States          15.13                        15.13
7667       2534  United States          12.16                        12.16
14049      8353   South Africa          11.77                        11.77
9233       2943          Spain          11.68                        11.68
843       14377          Egypt           11.2                        11.20
10218      4045         Canada          10.99                        10.99
3541       6550  United States      10.9 mg/L                        10.90
5380       4328  United States           10.5                        10.50
7601       2231          Spain           10.3                        10.30
6465       3745  United States           10.2                        10.20

In [165]:
pd.set_option("display.max_rows", 100)

df["Oxygen Saturation"].value_counts(dropna=False).head(100)

Oxygen Saturation
<NA>                                14022
100                                     4
105                                     3
99                                      3
91                                      2
No                                      2
29                                      1
0                                       1
15% at 5m                               1
77.3                                    1
115                                     1
3.95                                    1
137.6                                   1
229.1                                   1
241.3                                   1
119.36                                  1
>200                                    1
112 at 1m                               1
7.4                                     1
102.3                                   1
128                                     1
132 @ 0 m; 120 @ 5 m; 102 @ 10 m        1
66                                      1
108.3@1m                                1
101.8@4m                                1
115.55                                  1
17%                                     1
<20 (bottom)                            1
95.6                                    1
158                                     1
204                                     1
143.7                                   1
120%                                    1
0-130                                   1
137.2                                   1
43.5                                    1
143.6                                   1
167                                     1
97.89@1m                                1
107                                     1
111                                     1
132.7                                   1
127.6                                   1
108.1                                   1
96                                      1
126.2                                   1
108                                     1
93                                      1
94                                      1
85                                      1
98.3                                    1
98                                      1
90                                      1
100-120                                 1
100-126                                 1
89.9-133.6                              1
73.2-140                                1
102.7-108.                              1
111-122                                 1
86-183                                  1
98-122                                  1
111-174                                 1
104.5                                   1
30.1-31.5                               1
11.7                                    1
104-130                                 1
97-135.3                                1
8                                       1
86 - 97                                 1
74                                      1
103                                     1
Name: count, dtype: Int64

In [166]:
df["Oxygen Saturation"].dropna().unique()

<StringArray>
[                              '29',                              '115',
                             '77.3',                        '15% at 5m',
                                '0',                               'No',
                             '3.95',                            '137.6',
                            '229.1',                            '241.3',
                            '102.3',                              '128',
 '132 @ 0 m; 120 @ 5 m; 102 @ 10 m',                               '66',
                           '119.36',                             '>200',
                        '112 at 1m',                              '7.4',
                             '43.5',                            '143.6',
                              '167',                         '97.89@1m',
                         '108.3@1m',                         '101.8@4m',
                           '115.55',                              '17%',
                     '<20 (bottom)',                             '95.6',
                              '158',                              '204',
                            '143.7',                             '120%',
                            '0-130',                            '137.2',
                            '127.6',                            '132.7',
                              '111',                              '107',
                              '108',                               '96',
                               '91',                            '108.1',
                            '126.2',                              '105',
                               '93',                              '100',
                               '99',                               '94',
                               '85',                             '98.3',
                               '98',                               '90',
                          '100-120',                          '100-126',
                       '89.9-133.6',                         '73.2-140',
                       '102.7-108.',                          '111-122',
                           '86-183',                           '98-122',
                          '111-174',                            '104.5',
                        '30.1-31.5',                             '11.7',
                          '104-130',                         '97-135.3',
                                '8',                          '86 - 97',
                               '74',                              '103']
Length: 70, dtype: string

In [167]:
def parse_oxygen_saturation(value):
    if pd.isna(value):
        return np.nan

    text = str(value).strip().lower()

    # Text/non-measurements
    if text in ["no", "n.a.", "na"]:
        return np.nan

    # Don't guess inequality values
    if "<" in text or ">" in text:
        return np.nan

    # Multiple depth measurements are too complex to reduce safely
    if ";" in text:
        return np.nan

    # Remove percent sign
    cleaned = text.replace("%", "").strip()

    # Simple range
    range_match = re.fullmatch(
        r"(\d*\.?\d+)\s*-\s*(\d*\.?\d+)",
        cleaned
    )

    if range_match:
        low = float(range_match.group(1))
        high = float(range_match.group(2))
        return (low + high) / 2

    # Single measurement, optionally followed by depth information
    number_match = re.match(r"^(\d*\.?\d+)", cleaned)

    if number_match:
        return float(number_match.group(1))

    return np.nan

In [168]:
df["Oxygen Saturation Standardized"] = (
    df["Oxygen Saturation"].apply(parse_oxygen_saturation)
)

In [169]:
print(
    "Original oxygen saturation records:",
    df["Oxygen Saturation"].notna().sum()
)

print(
    "Standardized oxygen saturation records:",
    df["Oxygen Saturation Standardized"].notna().sum()
)

df["Oxygen Saturation Standardized"].describe()

Original oxygen saturation records: 79
Standardized oxygen saturation records: 74

count     74.000000
mean     101.007432
std       44.850268
min        0.000000
25%       91.875000
50%      103.750000
75%      116.412500
max      241.300000
Name: Oxygen Saturation Standardized, dtype: float64

In [170]:
df[
    [
        "Event ID",
        "Country",
        "Oxygen Saturation",
        "Oxygen Saturation Standardized"
    ]
].sort_values(
    "Oxygen Saturation Standardized",
    ascending=False
).head(10)

,Event ID,Country,Oxygen Saturation,Oxygen Saturation Standardized
3971,5456,United States,241.3,241.3
3626,4974,El Salvador,229.1,229.1
9230,2946,Spain,204,204.0
7001,3685,United States,167,167.0
8840,5745,Egypt,158,158.0
9233,2943,Spain,143.7,143.7
6998,3200,United States,143.6,143.6
13737,2580,France,111-174,142.5
3541,6550,United States,137.6,137.6
9712,1958,United States,137.2,137.2

In [171]:
df["Turbidity"].dropna().unique()

<StringArray>
[        '27',        '0.9',          '6',        '0.1',        '1.2',
          '1',       '4.31',        '1.6',        '3.3',       '15.3',
        '4.8',          '2',         'No',       '24.0',       '0.82',
 '9.67-19.46',       '13.0',       '32.6',        '9.7',        '120',
        '3.1',       '37.0',       '11.3',   '5.8-34.7',        '1.8',
          '3',        '2.8',        '3.2',        '4.1',        '4.0',
        '2.5',        '3.5',        '2.4',        '4.2',    '0.4-1.5',
        '2.2',        '3.8',        '4.3',         '10',         '12',
        '5.2',        '3-5',        '0.3',    '0.2-1.2',      '4.5-5',
        '0.4',        '0.5',        '2-3',       '>0.5',       '<0.5',
      '4.5-6',       '<1.0',        '< 1',         '13',          '7',
     '3.5-16',        '1.5',         '25',        '2.7',         '28',
        '1.1',        '8.7',        '4.5',         '31',        '1.9',
  '0.4 - 0.5']
Length: 66, dtype: string

In [172]:
print("Non-null turbidity records:", df["Turbidity"].notna().sum())

Non-null turbidity records: 87

In [173]:
def parse_turbidity(value):
    if pd.isna(value):
        return np.nan

    text = str(value).strip().lower()

    # Non-numeric response
    if text in ["no", "n.a.", "na"]:
        return np.nan

    # Inequalities don't give an exact measurement
    if "<" in text or ">" in text:
        return np.nan

    # Simple range -> midpoint
    range_match = re.fullmatch(
        r"(\d*\.?\d+)\s*-\s*(\d*\.?\d+)",
        text
    )

    if range_match:
        low = float(range_match.group(1))
        high = float(range_match.group(2))
        return (low + high) / 2

    # Single number
    if re.fullmatch(r"\d*\.?\d+", text):
        return float(text)

    return np.nan

In [174]:
df["Turbidity Standardized"] = (
    df["Turbidity"].apply(parse_turbidity)
)

In [175]:
print(
    "Original turbidity records:",
    df["Turbidity"].notna().sum()
)

print(
    "Standardized turbidity records:",
    df["Turbidity Standardized"].notna().sum()
)

df["Turbidity Standardized"].describe()

Original turbidity records: 87
Standardized turbidity records: 80

count     80.000000
mean       7.723063
std       15.141071
min        0.100000
25%        1.875000
50%        3.050000
75%        6.250000
max      120.000000
Name: Turbidity Standardized, dtype: float64

In [176]:
df[
    [
        "Event ID",
        "Country",
        "Turbidity",
        "Turbidity Standardized"
    ]
].sort_values(
    "Turbidity Standardized",
    ascending=False
).head(10)

       Event ID        Country Turbidity  Turbidity Standardized
7103       2637         France       120                  120.00
7119       2640         France      37.0                   37.00
7098       2638         France      32.6                   32.60
13771      2610         France        31                   31.00
13766      2608         France        28                   28.00
30        14541       Colombia        27                   27.00
13754      2605         France        25                   25.00
3626       4974    El Salvador      24.0                   24.00
9700       1970  United States  5.8-34.7                   20.25
1551      10182         France      15.3                   15.30

In [177]:
print("Non-null Secchi Disc records:", df["Secchi Disc"].notna().sum())

df["Secchi Disc"].dropna().unique()

Non-null Secchi Disc records: 143

<StringArray>
[        '26',       '0.05',          '7',         '14',         '15',
         '13',         '19',         '11',          '8',  '2.0 - 2.3',
 ...
       '7-14',      '0.6-4',  '2.25-5.25',   '0.38-5.7',    '0.3-1.4',
     '1 - 32',         '50',       '1.75', '1.75 - 2.5',   '1.5-12.5']
Length: 107, dtype: string

In [178]:
secchi_text_values = df[
    df["Secchi Disc"].notna() &
    df["Secchi Disc"].str.contains(r"[A-Za-z]", regex=True)
]["Secchi Disc"].unique()

secchi_text_values

<StringArray>
[               'No',             '0.5cm',        '0.6 to 3.5',
 'Min. 1.5 Max. 2.5', 'Min. 2.8 Max. 6.7',   '2.25min. 4.5max',
 'Min. 4.0 Max. 6.0', 'Min. 3.0 Max. 6.0', 'Min. 4.5 Max. 4.5',
 'Min. 2.1 Max. 2.1', 'Min. 2.0 Max. 4.0', 'Min. 3.0 Max. 4.0',
 'Min. 4.5 Max. 6.4', 'Min. 3.5 Max. 4.3', 'Min. 1.0 Max. 5.5',
 'Min. 3.0 Max. 5.0', 'Min. 1.0 Max. 4.0', 'Min. 3.5 Max. 5.0',
 'Min. 3.6 Max. 6.5',        'bottom 1.7',             'ca. 6',
         '1.5 to 14']
Length: 22, dtype: string

In [179]:
df[
    df["Secchi Disc"].notna() &
    df["Secchi Disc"].str.contains(
        r"cm|meter|metre|\bm\b",
        case=False,
        regex=True
    )
]["Secchi Disc"].value_counts()

Secchi Disc
0.5cm    1
Name: count, dtype: Int64

In [180]:
def parse_secchi(value):
    if pd.isna(value):
        return np.nan

    text = str(value).strip().lower()

    # Non-measurement
    if text in ["no", "n.a.", "na"]:
        return np.nan

    # Explicit centimeters -> convert to meters
    cm_match = re.fullmatch(r"(\d*\.?\d+)\s*cm", text)
    if cm_match:
        return float(cm_match.group(1)) / 100

    # Extract numbers
    numbers = re.findall(r"(?:\d+\.\d+|\.\d+|\d+)", text)
    numbers = [float(x) for x in numbers]

    if len(numbers) == 0:
        return np.nan

    # One measurement
    if len(numbers) == 1:
        return numbers[0]

    # Two measurements representing a range/min-max
    if len(numbers) == 2:
        if (
            "-" in text
            or " to " in text
            or ("min" in text and "max" in text)
        ):
            return sum(numbers) / 2

    return np.nan

In [181]:
df["Secchi Disc Meters"] = df["Secchi Disc"].apply(parse_secchi)

In [182]:
print(
    "Original Secchi Disc records:",
    df["Secchi Disc"].notna().sum()
)

print(
    "Standardized Secchi Disc records:",
    df["Secchi Disc Meters"].notna().sum()
)

df["Secchi Disc Meters"].describe()

Original Secchi Disc records: 143
Standardized Secchi Disc records: 141

count    141.000000
mean       6.838688
std       14.943186
min        0.005000
25%        2.000000
50%        3.800000
75%        6.000000
max      120.000000
Name: Secchi Disc Meters, dtype: float64

In [183]:
df[
    ["Event ID", "Country", "Secchi Disc", "Secchi Disc Meters"]
].sort_values(
    "Secchi Disc Meters",
    ascending=False
).head(10)

       Event ID   Country Secchi Disc  Secchi Disc Meters
13643       187    France         120             120.000
13246       268    France         120             120.000
13885       124    France          50              50.000
13064       286    France   1.25 - 60              30.625
30        14541  Colombia          26              26.000
13084       289    France    1.4 - 42              21.700
1426      13423     Spain          19              19.000
13873       155    France      1 - 32              16.500
13382       241    France          15              15.000
13384       240    France          15              15.000

In [184]:
df.loc[
    df["Secchi Disc"].str.contains("cm", case=False, na=False),
    ["Secchi Disc", "Secchi Disc Meters"]
]

     Secchi Disc  Secchi Disc Meters
3425       0.5cm               0.005

In [185]:
print(
    "Non-null Current Velocity records:",
    df["Current Velocity"].notna().sum()
)

df["Current Velocity"].dropna().unique()

Non-null Current Velocity records: 1855

<StringArray>
['32', 'n.a.', 'No', '0', 'slack', '1']
Length: 6, dtype: string

In [186]:
def parse_current_velocity(value):
    if pd.isna(value):
        return np.nan

    text = str(value).strip().lower()

    if text in ["n.a.", "na", "no", "slack"]:
        return np.nan

    try:
        return float(text)
    except ValueError:
        return np.nan

In [187]:
df["Current Velocity Standardized"] = (
    df["Current Velocity"].apply(parse_current_velocity)
)

In [188]:
print(
    "Original Current Velocity records:",
    df["Current Velocity"].notna().sum()
)

print(
    "Standardized Current Velocity records:",
    df["Current Velocity Standardized"].notna().sum()
)

df[
    ["Current Velocity", "Current Velocity Standardized"]
].value_counts(dropna=False)

Original Current Velocity records: 1855
Standardized Current Velocity records: 1850

Current Velocity  Current Velocity Standardized
<NA>              NaN                              12246
0                 0.0                               1846
1                 1.0                                  3
slack             NaN                                  2
No                NaN                                  2
32                32.0                                 1
n.a.              NaN                                  1
Name: count, dtype: int64

In [189]:
print(
    "Non-null Wind Velocity records:",
    df["Wind Velocity"].notna().sum()
)

df["Wind Velocity"].dropna().unique()

Non-null Wind Velocity records: 124

<StringArray>
[                '31',                  '1',                  '2',
                '2-4',                  '3',                  '5',
           '13.9 m/s',            '1.9 m/s',           '5.83 m/s',
             '3m/seg',
 ...
                 '37',              '10-15',              '7- 10',
               '8-12',            '< 2 m/s',             '4-8m/s',
        '15-20 m/sec',        '15 m/second',     '0 - 6 m/second',
 'Force 2 to force 3']
Length: 101, dtype: string

In [190]:
wind_text_values = df[
    df["Wind Velocity"].notna() &
    df["Wind Velocity"].str.contains(r"[A-Za-z]", regex=True)
]["Wind Velocity"].unique()

wind_text_values

<StringArray>
[            '13.9 m/s',              '1.9 m/s',             '5.83 m/s',
               '3m/seg',                   'No',             '1.74 m/s',
                 '3m/s',             '10 knots',       '0.4 - 5.0 ms-1',
 '2.1 - 6.4 (m3 s &#87',                'light',              '6 knots',
              '0-5 mph',             '2.83 m/s',             '7.27 m/s',
             '1.16 m/s',             '1.23 m/s',             '1.27 m/s',
               '10 mph',                 'Calm',              '0.5 m/s',
              '2.2 m/s',              '0.4 m/s',             '5.97 m/s',
              '1.3 m/s',              '4.9 m/s',              '4.6 m/s',
              '5.1 m/s',            '10-15 mph',                 'calm',
               '8.5m/s',              '2.7 m/s',             'very low',
              '1.7 kts',            '25 km h-1',  'less than 5 m per s',
           '5-10 knots',              '7-8 mph',            '275 m/seg',
                 'High',            '5-6 force',              '< 2 m/s',
               '4-8m/s',          '15-20 m/sec',          '15 m/second',
       '0 - 6 m/second',   'Force 2 to force 3']
Length: 47, dtype: string

In [191]:
df[
    df["Wind Velocity"].notna() &
    df["Wind Velocity"].str.contains(
        r"knot|kt",
        case=False,
        regex=True
    )
]["Wind Velocity"].value_counts()

Wind Velocity
10 knots      2
6 knots       1
1.7 kts       1
5-10 knots    1
Name: count, dtype: Int64

In [192]:
def parse_wind_velocity(value):
    if pd.isna(value):
        return np.nan

    text = str(value).strip().lower()

    # Qualitative / non-exact measurements
    if text in ["no", "calm", "light", "high", "very low", "n.a.", "na"]:
        return np.nan

    # Beaufort force descriptions
    if "force" in text:
        return np.nan

    # Inequalities are not exact values
    if "<" in text or ">" in text or "less than" in text:
        return np.nan

    numbers = re.findall(r"(?:\d+\.\d+|\.\d+|\d+)", text)
    numbers = [float(x) for x in numbers]

    if len(numbers) == 0:
        return np.nan

    # If range, use midpoint
    if len(numbers) == 2:
        value_num = sum(numbers) / 2
    elif len(numbers) == 1:
        value_num = numbers[0]
    else:
        return np.nan

    # Knots -> m/s
    if "knot" in text or "kts" in text:
        return value_num * 0.514444

    # mph -> m/s
    if "mph" in text:
        return value_num * 0.44704

    # km/h -> m/s
    if "km" in text and ("h" in text or "hour" in text):
        return value_num / 3.6

    # Explicit m/s variants
    if (
        "m/s" in text
        or "m/sec" in text
        or "m/second" in text
        or "m/seg" in text
        or "ms-1" in text
    ):
        return value_num

    # Plain numeric values: preserve as source-reported numeric values
    if re.fullmatch(r"\d*\.?\d+", text):
        return value_num

    # Plain numeric range
    if re.fullmatch(r"\d*\.?\d+\s*-\s*\d*\.?\d+", text):
        return value_num

    return np.nan

In [193]:
df["Wind Velocity Standardized"] = (
    df["Wind Velocity"].apply(parse_wind_velocity)
)

In [194]:
print(
    "Original Wind Velocity records:",
    df["Wind Velocity"].notna().sum()
)

print(
    "Standardized Wind Velocity records:",
    df["Wind Velocity Standardized"].notna().sum()
)

df["Wind Velocity Standardized"].describe()

Original Wind Velocity records: 124
Standardized Wind Velocity records: 108

count    108.000000
mean      18.197025
std       32.052325
min        0.000000
25%        3.000000
50%        5.985000
75%       23.250000
max      275.000000
Name: Wind Velocity Standardized, dtype: float64

In [195]:
df[
    [
        "Event ID",
        "Country",
        "Wind Velocity",
        "Wind Velocity Standardized"
    ]
].sort_values(
    "Wind Velocity Standardized",
    ascending=False
).head(15)

       Event ID     Country Wind Velocity  Wind Velocity Standardized
10251      4964  Costa Rica     275 m/seg                       275.0
10750      1593       Spain            98                        98.0
10437      1402       Spain            85                        85.0
10767      1588       Spain            68                        68.0
10751      1711       Spain            63                        63.0
10428      1557       Spain            60                        60.0
11866      1209       Spain            57                        57.0
10768      1590       Spain            57                        57.0
11867      1208       Spain            55                        55.0
11864      1183       Spain            55                        55.0
10749      1591       Spain            52                        52.0
11848      1207       Spain            50                        50.0
11862      1070       Spain            50                        50.0
11146      1371       Spain            49                        49.0
10756      1594       Spain            40                        40.0

In [196]:
standardized_cols = [
    "Water Temp Celsius",
    "Salinity Standardized",
    "Oxygen Content Standardized",
    "Oxygen Saturation Standardized",
    "Turbidity Standardized",
    "Secchi Disc Meters",
    "Current Velocity Standardized",
    "Wind Velocity Standardized"
]

df[standardized_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14101 entries, 0 to 14100
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Water Temp Celsius              642 non-null    float64
 1   Salinity Standardized           485 non-null    float64
 2   Oxygen Content Standardized     132 non-null    float64
 3   Oxygen Saturation Standardized  74 non-null     float64
 4   Turbidity Standardized          80 non-null     float64
 5   Secchi Disc Meters              141 non-null    float64
 6   Current Velocity Standardized   1850 non-null   float64
 7   Wind Velocity Standardized      108 non-null    float64
dtypes: float64(8)
memory usage: 881.4 KB

In [197]:
df[standardized_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Water Temp Celsius,642.0,19.736503,6.604735,0.000,15.4000,19.625,24.6000,38.5
Salinity Standardized,485.0,27.655766,9.832549,0.040,24.3000,31.300,34.7100,50.9
Oxygen Content Standardized,132.0,7.236705,3.573295,0.000,5.7875,6.700,8.2225,28.0
Oxygen Saturation Standardized,74.0,101.007432,44.850268,0.000,91.8750,103.750,116.4125,241.3
Turbidity Standardized,80.0,7.723063,15.141071,0.100,1.8750,3.050,6.2500,120.0
Secchi Disc Meters,141.0,6.838688,14.943186,0.005,2.0000,3.800,6.0000,120.0
Current Velocity Standardized,1850.0,0.018919,0.745035,0.000,0.0000,0.000,0.0000,32.0
Wind Velocity Standardized,108.0,18.197025,32.052325,0.000,3.0000,5.985,23.2500,275.0

In [198]:
import os

os.makedirs("data/processed", exist_ok=True)

In [199]:
output_path = "data/processed/harmful_algae_events_standardized.csv"

df.to_csv(output_path, index=False)

print("Saved to:", output_path)
print("Shape:", df.shape)

Saved to: data/processed/harmful_algae_events_standardized.csv
Shape: (14101, 94)

In [200]:
check_df = pd.read_csv(
    "data/processed/harmful_algae_events_standardized.csv",
    low_memory=False
)

print(check_df.shape)
print(check_df.columns[-8:].tolist())

(14101, 94)
['Water Temp Celsius', 'Salinity Standardized', 'Oxygen Content Standardized', 'Oxygen Saturation Standardized', 'Turbidity Standardized', 'Secchi Disc Meters', 'Current Velocity Standardized', 'Wind Velocity Standardized']

In [201]:
!git status --short

?? Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/

In [202]:
!git status --short --untracked-files=all

?? Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/

In [203]:
!git add data/processed/harmful_algae_events_standardized.csv

In [204]:
!git status --short

?? Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/

In [205]:
!git commit -m "Standardize categorical and numerical features"

On branch task3-standardization
Your branch is up to date with 'origin/task3-standardization'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/

nothing added to commit but untracked files present (use "git add" to track)

In [206]:
!git status

On branch task3-standardization
Your branch is up to date with 'origin/task3-standardization'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Oregon-State-University-1A-forecasting-risk-of-harmful-algal-blooms-in-coastal-marine-ecosystems/

nothing added to commit but untracked files present (use "git add" to track)

In [207]:
!git push -u origin task3-standardization

branch 'task3-standardization' set up to track 'origin/task3-standardization'.
Everything up-to-date